vmcs: Remove unused sm_cache_map_vector definition (#1411)
The code using it also ifdef'ed with 0, anyyd gcc 6
complains

error: 'sm_cache_map_vector' defined but not used

The code using it also ifdef'ed out

Signed-off-by: Khem Raj <raj.khem@gmail.com>